'use strict';
const assert=require('node:assert/strict'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.argv[3]||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});let checks=0;
 try{for(const language of ['ko','en'])for(const width of [1440,390])for(const dark of [false,true]){
  const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],network=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
  const ready=()=>page.waitForSelector('html[data-ready=true]');
  await page.goto(pathToFileURL(path.resolve(process.argv[2],language,'features/project.html')).href);await ready();
  if(dark)await page.locator('#theme-toggle').click();
  const data=await page.locator('#s2s-data').evaluate(node=>JSON.parse(node.textContent));
  assert.equal(await page.locator('.project-composition').count(),1);
  assert.equal(await page.locator('.feature-overview').count(),3,'Each actual capability has its own group');
  assert.equal(await page.locator('.atlas-area-open:visible').count(),0,'No area selection is required to read a feature flow');
  const feature=page.locator('.feature-overview').first(),child=data.featureDetails[0];
  assert(!(await feature.innerText()).includes('SECOND ONLY'),'Shared ownership does not blend two capability traces');
  assert((await page.locator('#feature-cap-second').innerText()).includes('SECOND ONLY'));
  for(const value of [...child.summary.inputs,...child.summary.outputs])assert((await feature.locator('.feature-request').innerText()).includes(value));
  assert((await feature.locator('.feature-request').boundingBox()).y<(await feature.locator('.feature-step').first().boundingBox()).y);
  assert.equal(await feature.locator('.feature-step').count(),2);
  assert(child.nodes.length>await feature.locator('.feature-step').count(),'Overview combines internal steps into responsibilities');
  assert(!(await feature.innerText()).includes('DETAILED RECEIVE'),'Internal processing stays in the detail page');
  assert.equal(await page.locator('.feature-overview select').count(),0,'Scenario controls belong to detail');
  const ids=await feature.locator('[data-edge-id]').evaluateAll(nodes=>nodes.map(node=>node.dataset.edgeId));
  assert(ids.every(id=>child.edges.some(edge=>edge.id===id)),'Arrows use only the exact child graph');
  assert((await page.locator('#feature-cap-second .feature-relations').innerText()).includes(language==='ko'?'병렬':'Parallel'));
  assert.equal(await page.locator('#feature-cap-second .feature-connector').count(),0,'Parallel transfers are not serialized by card order');
  await feature.locator('a.feature-open').click();await page.waitForURL(url=>url.pathname.endsWith('/features/behavior.html'));await ready();
  assert.equal(await page.locator('#mode').inputValue(),'detail','All-processing action opens every recorded node');
  assert.equal(await page.locator('#mode option:checked').innerText(),language==='ko'?'전체 처리':'All processing');
  assert.equal(await page.locator('.node').count(),child.nodes.length);
  await page.locator('#mode').selectOption('core');
  assert.equal(await page.locator('.node').count(),child.nodes.filter(node=>node.importance==='core').length);
  await page.locator('#mode').selectOption('detail');
  assert.equal(await page.locator('.node').count(),child.nodes.length);
  await page.locator('#links a[href*="project.html"]').click();await page.waitForURL(url=>url.pathname.endsWith('/features/project.html'));await ready();
  await page.locator('.feature-jumps a').first().click();
  assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('feature'),child.subject.id);
  await page.waitForFunction(()=>document.activeElement?.matches('.feature-heading.is-selected'));
  const box=feature.locator('.feature-step[data-group-id="group-request"]');await box.focus();
  await Promise.all([page.waitForURL(url=>url.pathname.endsWith('/features/behavior.html')),page.keyboard.press('Enter')]);await ready();
  assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('item'),'group-request');
  assert.equal(await page.locator('.region-process').count(),2);
  assert((await page.locator('.region-processes').innerText()).includes('DETAILED RECEIVE'));
  assert.equal(await page.locator('.node.group-member').count(),2);
  await page.locator('.region-process[data-node-id="node-caller"]').click();
  assert.equal(await page.locator('.node.selected').getAttribute('data-id'),'node-caller');
  await page.locator('#close-panel').click();
  await page.locator('.node[data-id="node-main"]').click();
  assert.equal(await page.locator('.node.selected').getAttribute('data-id'),'node-main');
  assert(await page.locator('#panel').evaluate(node=>node.classList.contains('open')));
  await page.locator('.node-rules a').click();await ready();
  assert.equal(new URL(page.url()).searchParams.get('s2s-node'),'node-main');
  await page.locator('.primer-intro > .links a[data-layer="atlas"]').click();await ready();
  assert.equal(await page.locator('.feature-heading.is-selected').getAttribute('data-feature-id'),child.subject.id);
  assert(await page.locator('.feature-heading.is-selected').evaluate(node=>node===document.activeElement));
  assert.equal(await page.locator('#feature-cap-missing .feature-step').count(),0);
  await page.locator('#feature-cap-missing button.feature-open').click();assert(await page.locator('#entry-context').isVisible());await page.keyboard.press('Escape');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.goto(pathToFileURL(path.resolve(process.argv[2],language,'features/no-summary.html')).href);await ready();
  assert.equal(await page.locator('.feature-step').count(),0,'Missing reviewed summaries do not become detailed-node copies');
  assert.equal(await page.locator('.feature-request').count(),2,'Known inputs/results remain available');
  assert.equal(await page.locator('.feature-overview a.feature-open').count(),2,'Checked detail pages remain accessible');
  assert.deepEqual(errors,[]);assert.deepEqual(network,[]);await context.close();checks++;
 }}finally{await browser.close()}
 console.log(checks+' summary/detail journeys passed: reviewed responsibilities, hidden internal steps, scoped process lists, parallel relations, node rules, return focus and offline use.');
})().catch(error=>{console.error(error);process.exitCode=1});
