/* Diagram → data flow → node rule picture → selected position, offline. */
'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.argv[3]||'playwright');

(async()=>{
  const browser=await chromium.launch({headless:true});
  let checks=0;
  try {
    for(const language of ['ko','en'])for(const width of [1440,390])for(const dark of [false,true]) {
      const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});
      const page=await context.newPage(),errors=[],external=[];
      page.on('pageerror',error=>errors.push(error.message));
      page.on('request',request=>{if(/^https?:/.test(request.url()))external.push(request.url());});
      const root=path.resolve(process.argv[2],language);
      const url=file=>pathToFileURL(path.join(root,file)).href;
      const ready=()=>page.waitForSelector('html[data-ready="true"]');
      const noOverflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
      await page.goto(url('journey/project.html'));await ready();
      if(dark)await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#entry-catalog').evaluate(node=>node.open),false,'The first picture precedes the catalog');
      assert(await page.locator('#entry-map').isVisible());
      assert.equal(await page.locator('#entry-reading-path [aria-current="step"]').innerText(),language==='ko'?'영역 선택':'Choose area');
      assert.equal(await page.locator('#entry-map .code-name,#entry-map .location').count(),0,'Implementation metadata stays on demand');
      const mapData=await page.locator('#s2s-data').evaluate(node=>JSON.parse(node.textContent));
      const feature=mapData.subjects[0];
      assert.equal(await page.locator('#entry-map .atlas-map-edges,#entry-map-fit').count(),0,'The area overview has no graph canvas or fit-to-screen zoom');
      assert.equal(await page.locator('.atlas-feature-link[data-feature-id]').count(),0,'Nested capabilities stay inside their area');
      assert.equal(await page.locator('.atlas-area-card:visible').count(),1,'Only root areas are shown; shared support is separate');
      assert.equal(await page.locator('#entry-map-stage').evaluate(node=>getComputedStyle(node).transform),'none');
      const boundaries=await page.locator('[data-edge-ids]').evaluateAll(nodes=>nodes.flatMap(node=>JSON.parse(node.dataset.edgeIds)));
      assert(boundaries.includes('edge-dependency'));assert(!boundaries.includes('edge-call'),'Internal calls do not become inter-area transfers');
      assert(boundaries.every(id=>mapData.edges.some(edge=>edge.id===id)));
      await page.locator('#entry-diagram').click();
      const parentBounds=await page.locator('.map-region[data-id="region-domain"]').boundingBox();
      const childBounds=await page.locator('.map-region[data-id="region-main"]').boundingBox();
      assert(parentBounds&&childBounds,'Nested regions also render in the detailed structure view');
      assert(childBounds.x>=parentBounds.x-1&&childBounds.y>=parentBounds.y-1);
      assert(childBounds.x+childBounds.width<=parentBounds.x+parentBounds.width+1&&childBounds.y+childBounds.height<=parentBounds.y+parentBounds.height+1);
      await page.locator('#entry-home').click();
      const area=page.locator('.atlas-area-open[data-open-area="region-domain"]');
      await area.focus();await page.keyboard.press('Enter');
      assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('area'),'region-domain');
      assert.equal(await page.locator('.atlas-feature-link[data-feature-id]').count(),0);
      await page.locator('.atlas-area-open[data-open-area="region-main"]').click();
      await page.reload();await ready();
      assert.equal(await page.locator('#entry-area-breadcrumb [aria-current]').textContent(),mapData.regions.find(group=>group.id==='region-main').label);
      assert.equal(await page.locator('#entry-reading-path [aria-current="step"]').innerText(),language==='ko'?'기능 선택':'Choose capability');
      assert.equal(await page.locator('.atlas-area-context').evaluate(node=>node.open),false,'Previously read area content is secondary');
      assert((await page.locator('.atlas-feature-link').first().boundingBox()).y<(await page.locator('.atlas-area-context').boundingBox()).y,'Area navigation reaches capability choices before repeating its overview');
      const contract=mapData.regions.find(group=>group.id==='region-main').interface;
      await page.locator('.atlas-area-context > summary').click();
      for(const value of [...contract.inputs,contract.activity,...contract.outputs,contract.actor])assert((await page.locator('.atlas-area-card').textContent()).includes(value));
      assert.equal(await page.locator('.atlas-example-artifact').count(),2);
      assert((await page.locator('.atlas-example-artifact').first().textContent()).includes('<request> & example'));
      assert.equal(await page.locator('.atlas-example-artifact request').count(),0,'Examples are literal text, not executable markup');
      await page.locator('.atlas-area-related > summary').click();
      await page.locator('.atlas-area-transfer.dependency [data-open-area="region-support"]').click();
      await page.locator('.atlas-area-context > summary').click();
      assert(await page.locator('.atlas-area-missing').first().isVisible(),'Older data does not invent area inputs');
      await page.goBack();await ready();
      assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('area'),'region-main');
      const entry=page.locator('.atlas-feature-link[data-feature-id="'+feature.id+'"]');
      assert.equal(await entry.evaluate(node=>node.tagName),'A','Generated single capability opens directly');
      if(width<720)assert(await page.locator('#entry-map').evaluate(node=>node.scrollWidth<=node.clientWidth+1),'Narrow connection view remains readable without horizontal panning');
      await noOverflow();
      await entry.focus();await page.keyboard.press('Enter');await ready();
      assert(page.url().includes('/journey/behavior.html'));
      assert.equal(await page.locator('.reading-path [aria-current="step"]').innerText(),language==='ko'?'처리 과정':'Process');
      const state=new URLSearchParams(new URL(page.url()).search).get('s2s-atlas');
      assert.equal(new URLSearchParams(state.slice(1)).get('feature'),feature.id);
      assert.equal(new URLSearchParams(state.slice(1)).get('area'),'region-main');
      await page.locator('.node[data-id="node-main"]').click();
      assert.equal(await page.locator('.node-data-item strong').textContent(),language==='ko'?'판단 결과':'Decision result');
      assert(!(await page.locator('.node-rules').textContent()).includes(language==='ko'?'별도 처리의 합성 규칙':'Synthetic rule for the separate step'));
      assert.equal(await page.locator('.node-reference').first().evaluate(node=>node.open),false);
      const lesson=page.locator('.node-rules a');
      await lesson.focus();await page.keyboard.press('Enter');await ready();
      assert.equal(new URL(page.url()).searchParams.get('s2s-node'),'node-main');
      assert.equal(await page.locator('.reading-path [aria-current="step"]').innerText(),language==='ko'?'조건·결과 그림':'Condition & result pictures');
      assert(await page.locator('#figure-cancellation').isVisible());
      assert(!(await page.locator('#figure-separate').isVisible()),'Another node must not leak into this lesson');
      assert(await page.locator('.node-lesson-context').isVisible());
      await page.locator('.node-lesson-context button').click();
      assert(await page.locator('#figure-separate').isVisible(),'The full lesson remains reachable');
      await noOverflow();
      await page.locator('.primer-intro > .links a[data-layer="behavior"]').click();await ready();
      assert.equal(await page.locator('.node.selected').getAttribute('data-id'),'node-main');
      assert(await page.locator('#panel').evaluate(node=>node.classList.contains('open')));
      await page.locator('#links a').filter({hasText:language==='ko'?'프로젝트 지도':'Project map'}).click();await ready();
      const returned=page.locator('.atlas-feature-link.is-selected');
      assert.equal(await returned.getAttribute('data-feature-id'),feature.id);
      assert(await returned.evaluate(node=>node===document.activeElement),'Return restores keyboard focus');
      const bounds=await returned.boundingBox();assert(bounds.y>=0&&bounds.y+bounds.height<=1001);
      await page.goto(url('entry-missing.html'));await ready();
      await page.locator('.atlas-area-open[data-open-area="region-main"]').click();
      const missing=page.locator('.atlas-feature-link[data-feature-id]');
      assert.equal(await missing.evaluate(node=>node.tagName),'BUTTON');
      await missing.click();assert(await page.locator('#entry-context').isVisible(),'Missing details expose scoped context');
      await page.keyboard.press('Escape');
      await noOverflow();
      const invalid=new URL(page.url());invalid.hash=new URLSearchParams({s2s:'1',subject:mapData.subject.id,view:'overview',area:'missing-area'});
      await page.goto(invalid.href);await ready();
      assert(await page.locator('#navigation-notice').isVisible());
      await page.goto(url('journey/uncertain.html'));await ready();
      assert(await page.locator('.atlas-area-card.uncertain .atlas-area-missing').isVisible());
      assert.equal(await page.locator('#entry-map .atlas-example-artifact').count(),0,'Uncertain regions withhold illustrative artifacts');
      await noOverflow();
      assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
      await context.close();checks++;
    }
  } finally {await browser.close();}
  console.log(checks+' learning journeys passed: nested areas, reviewed interfaces, boundary transfers, labeled data, isolated node lessons, context return, missing detail, themes and offline use.');
})().catch(error=>{console.error(error);process.exitCode=1;});
